contentColumnType: string
fieldGroup: 2c17a2e7-ef8b-4632-890e-fc15f2d105cf # Work
handle: desktopImage
instructions: 'Add a desktop screenshot'
name: 'Desktop Image'
searchable: true
settings:
  defaultUploadLocationSource: 'volume:9f3564bf-b786-4937-88c9-94c1ae067da3' # images
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: ''
  selectionLabel: ''
  singleUploadLocationSource: 'volume:9f3564bf-b786-4937-88c9-94c1ae067da3' # images
  singleUploadLocationSubpath: ''
  sources:
    - 'volume:9f3564bf-b786-4937-88c9-94c1ae067da3' # images
  useSingleFolder: ''
  viewMode: large
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
