contentColumnType: text
fieldGroup: 4ea542e5-b965-4dd1-8f79-60e0bf3eb2c1 # Testimonials
handle: personUrl
instructions: ''
name: 'Person URL'
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
