baseUrl: 'http://valentin.escoyez.be'
handle: en_us
hasUrls: true
language: en-US
name: 'Valentin Escoyez (en-US)'
primary: true
siteGroup: ff895e70-1ab1-4d39-a82e-4ca5225669c8 # Valentin Escoyez (en-US)
sortOrder: 1
